name: story_view_advance
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.2.0
homepage: https://github.com/gauhun/story_view_advance

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  rxdart: ^0.28.0
  video_player: ^2.9.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
